### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'; essentia installs fine, but gaia fails https://github.com/MTG/homebrew-essentia/issues/22

### ISSUE THREAD

**Issue by alisonbma** [MTG/essentia-docker#10]
Issues when running: `brew install essentia --HEAD`

ModuleNotFoundError: No module named 'setuptools'; essentia installs fine, but gaia fails https://github.com/MTG/homebrew-essentia/issues/22

Please let me know if this can be fixed!

**Comment by alastair** [comment]
Hi, I think this is an error report related to installing essentia on macos with homebrew and therefore shouldn't be reported in this repository. I'll close this issue, if you continue to have problems then please open another issue in the [MTG/homebrew-essentia](https://github.com/MTG/homebrew-essentia) repository
