### ISSUE TITLE
The executable is not found 

### ISSUE THREAD

**Issue by francoiscabrol** [MTG/essentia-docker#5]
After having pulled the image with `docker pull mtgupf/essentia`
I ran the command `docker run -ti --rm -v `pwd`:/essentia mtgupf/essentia essentia_streaming_extractor_music audio.wav audio.sig`

And I got the error: `docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"essentia_streaming_extractor_music\": executable file not found in $PATH": unknown.`
If I look into the container I don't find the essentia_streaming_extractor_music executable...

The image was pulled correctly so I don't see what I missed. I run docker under macos but it should not change anything.

**Comment by dbogdanov** [comment]
Please, try to pull again, some of the images were missing the executables.

**Comment by francoiscabrol** [comment]
Thank you it's working!
