### ISSUE TITLE
Python executable name

### ISSUE THREAD

**Issue by Oeyvind** [MTG/essentia-docker#8]
The python executable in the docker (latest) is named python3, but the example on the readme page uses "python".
It would be nice if this could be the same name, so that the documentation example would run out of the box.

**Comment by alastair** [comment]
Thanks for the report. The python executable was updated in the README in this repo, but not in the docker hub readme.

I took this chance to also update the ubuntu images to the latest LTS and latest release, and update the readme on dockerhub.
